[tool.poetry]
name = "qat-rpc"
version = "0.1.0"
description = "RPC tooling for OQC QAT."
authors = ["Kajsa Eriksson Rosenqvist <keriksson.rosenqvist@oxfordquantumcircuits.com>"]
readme = "README.md"
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"

[tool.poetry.group.dev.dependencies]
coverage = "^6.3.2"
pytest-cov = "~=2.10.1"

[tool.poetry.group.licenses]
optional = true

[tool.poetry.group.licenses.dependencies]
pip-licenses = "^3.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
