name: Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: write

run-name: Build from ${{ github.ref }}

jobs:
  formatting-tests:
    name: Consistency and formatting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Formatting tests
        run: |
          poetry install --sync --with dev
          poetry run black --check .
          poetry run isort --check .
          poetry run autoflake --check .
          poetry run pip-audit --desc
          poetry run pip-licenses

  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Unit tests
        run: |
          poetry install --sync
          poetry run pytest -v src/tests/

